import {parseInput, searchUrl, address, ratingInfo, formatDate, officialUrl, distanceKm, validCoordinates} from './core.js';
export function start(adapter) {
 const $=id=>document.getElementById(id), node=(tag,cls,text)=>{const n=document.createElement(tag);n.className=cls||'';if(text!==undefined)n.textContent=text;return n;};
 let items=[],recent=[],coords=null,view='list',active=null,page=1,totalPages=1,run=0,controller=null,locationRun=0;
 const filters=()=>({radius:Number($('radius').value),rating:$('rating').value,type:$('type').value,sort:$('sort').value});
 const status=t=>$('status').textContent=t;
 function cancel(){++run;controller?.abort();$('search').disabled=false;$('more').disabled=false;}
 const point=b=>{const g=b.geocode;if(!g||g.latitude==null||g.longitude==null||g.latitude===''||g.longitude==='')return null;const lat=Number(g.latitude),lon=Number(g.longitude);return validCoordinates(lat,lon)&&!(lat===0&&lon===0)?{lat,lon}:null;};
 const miles=b=>{const p=point(b);return coords&&p?distanceKm(coords,p)/1.609344:null;};
 function visible(){const f=filters();return items.filter(b=>{const r=ratingInfo(b),v=Number(r.value),m=miles(b);return (m===null||m<=f.radius)&&(f.rating==='all'||f.rating==='pass'&&r.value==='Pass'||f.rating==='other'&&!r.numeric&&r.value!=='Pass'||f.rating==='low'&&r.numeric&&v<=2||/^\d$/.test(f.rating)&&r.numeric&&v>=Number(f.rating))&&(f.type==='all'||f.type==='other'&&![1,7843,7844].includes(Number(b.BusinessTypeID))||String(b.BusinessTypeID)===f.type);}).sort((a,b)=>f.sort==='name'?a.BusinessName.localeCompare(b.BusinessName):f.sort==='rating'?(ratingInfo(b).numeric?Number(b.RatingValue):-1)-(ratingInfo(a).numeric?Number(a.RatingValue):-1):((miles(a)??Infinity)-(miles(b)??Infinity))||a.BusinessName.localeCompare(b.BusinessName));}
 function row(b){const r=ratingInfo(b),button=node('button','card'),main=node('span','main'),m=miles(b);main.append(node('strong','',b.BusinessName),node('small','',address(b)||'Address not published'),node('small','',`${b.BusinessType||'Other'}${m===null?'':' · '+m.toFixed(1)+' mi'}`));const badge=node('span','badge '+r.tone+(r.numeric?'':' text'),r.value==='Improvement required'?'Improve':r.value.startsWith('Awaiting')?'Pending':r.value);badge.title=r.value;badge.setAttribute('aria-label',r.value);if(r.numeric)badge.append(node('small','','out of 5'));button.append(main,badge);button.onclick=()=>detail(b);return button;}
 function detail(b){$('detail-title').textContent=b.BusinessName;const r=ratingInfo(b),c=$('detail-content');c.replaceChildren(node('p','muted',address(b)||'Address not published'),node('div','score',r.value),node('p','',r.label),node('p','','Last inspected: '+formatDate(b.RatingDate)));if(b.NewRatingPending)c.append(node('p','','A new rating is pending.'));if(adapter.preview)c.append(node('p','hint','Fictional demonstration record — not an official rating.'));else{const a=node('a','link','Official record');a.href=officialUrl(b.FHRSID);a.target='_blank';a.rel='noopener noreferrer';c.append(a);}if(!$('detail').open)$('detail').showModal();recent=[b,...recent.filter(x=>x.FHRSID!==b.FHRSID)].slice(0,4);renderRecent();}
 function renderRecent(){$('recent-section').hidden=!recent.length;$('recent').replaceChildren(...recent.map(row));}
 function render(){const list=visible();$('count').textContent=list.length+' results';$('filter-summary').textContent=$('rating').selectedOptions[0].textContent+' · '+filters().radius+' mi';$('results').replaceChildren(...list.map(row));if(!list.length)$('results').append(node('p','empty',items.length?'No results match these filters.':'Search a name or use Near me.'));$('results').hidden=view!=='list';$('map-panel').hidden=view!=='map';$('list-view').setAttribute('aria-pressed',String(view==='list'));$('map-view').setAttribute('aria-pressed',String(view==='map'));$('more').hidden=!active||page>=totalPages;renderMap(list);}
 function renderMap(list){const root=$('map');root.replaceChildren(node('span','north','N ↑ · Relative positions'));const pins=list.map(b=>({b,p:point(b)})).filter(x=>x.p);const lats=pins.map(x=>x.p.lat),lons=pins.map(x=>x.p.lon);const minLat=Math.min(...lats),maxLat=Math.max(...lats),minLon=Math.min(...lons),maxLon=Math.max(...lons);pins.forEach(({b,p},i)=>{const r=ratingInfo(b),pin=node('button','pin',r.numeric?r.value:r.value==='Pass'?'P':'?');pin.style.left=(12+76*(maxLon===minLon?.5:(p.lon-minLon)/(maxLon-minLon)))+'%';pin.style.top=(16+68*(maxLat===minLat?.5:(maxLat-p.lat)/(maxLat-minLat)))+'%';pin.setAttribute('aria-label',b.BusinessName+' · '+r.value);pin.title=b.BusinessName;pin.onclick=()=>detail(b);root.append(pin);});$('map-note').textContent=`${pins.length} pins · ${list.length-pins.length} without coordinates. Relative positions only; no street map. Overlapping pins can be opened from List.`;}
 async function search(more=false){const ticket=++run;controller?.abort();controller=new AbortController();let q=active;if(!more){const parsed=parseInput($('query').value);if(parsed.issue&&($('query').value.trim()||!$('area').value.trim()&&!coords)){status(parsed.issue);return;}q={id:parsed.id,name:parsed.name,area:$('area').value.trim()||parsed.area,coordinates:coords||parsed.coordinates,radius:filters().radius,page:1};if(!q.id&&!q.name&&!q.area&&!q.coordinates){status('Enter a business name, town or postcode, or use Near me.');return;}coords=q.coordinates;active=q;page=0;items=[];totalPages=1;render();}status('Searching…');$('search').disabled=true;$('more').disabled=true;try{const data=await adapter.search({...q,page:page+1},controller.signal);if(ticket!==run)return;if(!Array.isArray(data.establishments))throw Error('Unexpected ratings response. Please try again.');const unique=new Map([...items,...data.establishments].map(b=>[b.FHRSID,b]));items=[...unique.values()];page++;totalPages=Number(data.meta?.totalPages)||1;render();status(`${adapter.preview?'Demo results':'Live FSA results'}${totalPages>page?' · Filters apply to loaded results; load more for other matches.':''}${!items.length?' · No matches found.':''}`);}catch(e){if(ticket===run)status(e.name==='AbortError'?'Request cancelled. Try again.':e.message||'Could not load ratings.');}finally{if(ticket===run){$('search').disabled=false;$('more').disabled=false;}}}
 $('search-form').onsubmit=e=>{e.preventDefault();search();};$('more').onclick=()=>search(true);
 $('near').onclick=async()=>{if(coords){cancel();locationRun++;coords=null;active=null;items=[];render();$('near').textContent='Near me';$('location-note').textContent='Location off';status('Location removed.');return;}const ticket=++locationRun;$('near').disabled=true;status(adapter.preview?'Simulating location…':'Requesting location…');try{const p=await adapter.locate();if(ticket!==locationRun)return;coords=p;$('area').value='';$('near').textContent='Location on';$('location-note').textContent=adapter.preview?'Simulated location · tap Location on to clear':'Location sent to FSA for this search · tap Location on to clear';await search();}catch{if(ticket===locationRun)status('Location unavailable. Enter a town or postcode.');}finally{$('near').disabled=false;}};
 $('area').oninput=()=>{cancel();locationRun++;coords=null;active=null;items=[];render();$('near').textContent='Near me';$('location-note').textContent='Location off';};
 $('filters').onclick=()=>$('filter-dialog').showModal();$('filter-form').onsubmit=e=>{e.preventDefault();$('filter-dialog').close();if(active&&active.radius!==filters().radius&&coords)search();else render();};$('reset').onclick=()=>{$('radius').value='2';$('rating').value='all';$('type').value='all';$('sort').value='distance';};
 $('list-view').onclick=()=>{view='list';render();};$('map-view').onclick=()=>{view='map';render();};$('clear').onclick=()=>{recent=[];renderRecent();};
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('help').onclick=$('about').onclick=()=>$('help-dialog').showModal();
 $('privacy').textContent=adapter.preview?'Offline demo. Fictional records and simulated location. No network requests, real location access, or saved history.':'Search terms and, after Near me, coordinates are sent to the FSA. Your hosting provider and the FSA receive ordinary web requests, including your IP address. No analytics or advertising. Searches, coordinates and recent checks stay in memory only; the service worker caches only app files. Closing or reloading clears this session. Opening an official record visits the FSA website.';
 render();if(adapter.preview){items=adapter.items;status('Offline demo · fictional businesses');render();}
}
